#appveyor.yml reference: http://www.appveyor.com/docs/appveyor-yml
#version: 0.25.1.{build}
#platform: x86
clone_folder: c:\gittfs
# build cache to preserve files/folders between builds
cache:
  - packages -> paket.lock  # preserve "packages" directory in the root of build folder but will reset it if `paket.lock` is modified
init: []
#before_build:
#  - ps: $env:Config = "Release"
build_script:
- ps: |
    if($env:target -eq $null)
    {
      $target = "AppVeyorBuild"
      echo "target: $target"
      .\build.ps1 -Target "$target" -ScriptArgs '-isDryRun=true -gitHubUserAccount"$env:gitHubUserAccount" -gitHubToken="$env:gitHubToken" -chocolateyToken="$env:chocolateyToken"'
      #$UseDryRun = "false"
    }
    else
    {
      $target = $env:target
      echo "target: $target"
      .\build.ps1 -Target "$target" -ScriptArgs '-isDryRun=false -gitHubUserAccount"$env:gitHubUserAccount" -gitHubToken="$env:gitHubToken" -chocolateyToken="$env:chocolateyToken"'
      #$UseDryRun = "true"
    }

test: off
